/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package Iou {
    final case class Iou_Merge(otherCid: ` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]) extends ` lfdomainapi`.ValueRef

    object Iou_Merge extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou], _root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val otherCid: ` C`[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val otherCid = ` f`(` view`.otherCid)
          };
          new $anon()
        }
      };
      implicit val `Iou_Merge Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] {
          override def write(value: _root_.com.daml.quickstart.iou.model.Iou.Iou_Merge): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("otherCid", ` lfdomainapi`.Value.encode(value.otherCid)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "otherCid"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]](zv0) match {
                case _root_.scala.Some(otherCid) => Some(Iou_Merge(otherCid))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.Iou, "Iou", "Iou_Merge");
      implicit def `Iou_Merge LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] = {
            object `view ` extends view[lte.Field] {
              val otherCid = lte.field("otherCid", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.Iou.Iou_Merge] = lte.RecordFields.xmapN(lte.fields(`view `.otherCid))({
                case otherCid => _root_.com.daml.quickstart.iou.model.Iou.Iou_Merge(otherCid)
              })({
                case _root_.com.daml.quickstart.iou.model.Iou.Iou_Merge(otherCid) => otherCid
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
