/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package Iou {
    final case class Iou_Split(splitAmount: ` lfdomainapi`.Primitive.Numeric) extends ` lfdomainapi`.ValueRef

    object Iou_Split extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.Numeric, _root_.com.daml.quickstart.iou.model.Iou.Iou_Split] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val splitAmount: ` C`[` lfdomainapi`.Primitive.Numeric];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val splitAmount = ` f`(` view`.splitAmount)
          };
          new $anon()
        }
      };
      implicit val `Iou_Split Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.Iou.Iou_Split] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.Iou.Iou_Split] {
          override def write(value: _root_.com.daml.quickstart.iou.model.Iou.Iou_Split): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("splitAmount", ` lfdomainapi`.Value.encode(value.splitAmount)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.Iou.Iou_Split] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "splitAmount"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Numeric](zv0) match {
                case _root_.scala.Some(splitAmount) => Some(Iou_Split(splitAmount))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.Iou, "Iou", "Iou_Split");
      implicit def `Iou_Split LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_Split] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_Split] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.Iou.Iou_Split] = {
            object `view ` extends view[lte.Field] {
              val splitAmount = lte.field("splitAmount", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Numeric](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.Iou.Iou_Split] = lte.RecordFields.xmapN(lte.fields(`view `.splitAmount))({
                case splitAmount => _root_.com.daml.quickstart.iou.model.Iou.Iou_Split(splitAmount)
              })({
                case _root_.com.daml.quickstart.iou.model.Iou.Iou_Split(splitAmount) => splitAmount
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
