/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package Iou {
    final case class Iou_Transfer(newOwner: ` lfdomainapi`.Primitive.Party) extends ` lfdomainapi`.ValueRef

    object Iou_Transfer extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.Party, _root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val newOwner: ` C`[` lfdomainapi`.Primitive.Party];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val newOwner = ` f`(` view`.newOwner)
          };
          new $anon()
        }
      };
      implicit val `Iou_Transfer Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] {
          override def write(value: _root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("newOwner", ` lfdomainapi`.Value.encode(value.newOwner)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "newOwner"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv0) match {
                case _root_.scala.Some(newOwner) => Some(Iou_Transfer(newOwner))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.Iou, "Iou", "Iou_Transfer");
      implicit def `Iou_Transfer LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] = {
            object `view ` extends view[lte.Field] {
              val newOwner = lte.field("newOwner", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer] = lte.RecordFields.xmapN(lte.fields(`view `.newOwner))({
                case newOwner => _root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer(newOwner)
              })({
                case _root_.com.daml.quickstart.iou.model.Iou.Iou_Transfer(newOwner) => newOwner
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
