/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package IouTrade {
    final case class IouTrade_Accept(quoteIouCid: ` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]) extends ` lfdomainapi`.ValueRef

    object IouTrade_Accept extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou], _root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val quoteIouCid: ` C`[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val quoteIouCid = ` f`(` view`.quoteIouCid)
          };
          new $anon()
        }
      };
      implicit val `IouTrade_Accept Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] {
          override def write(value: _root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("quoteIouCid", ` lfdomainapi`.Value.encode(value.quoteIouCid)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "quoteIouCid"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]](zv0) match {
                case _root_.scala.Some(quoteIouCid) => Some(IouTrade_Accept(quoteIouCid))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.IouTrade, "IouTrade", "IouTrade_Accept");
      implicit def `IouTrade_Accept LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] = {
            object `view ` extends view[lte.Field] {
              val quoteIouCid = lte.field("quoteIouCid", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.Iou.Iou]](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept] = lte.RecordFields.xmapN(lte.fields(`view `.quoteIouCid))({
                case quoteIouCid => _root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept(quoteIouCid)
              })({
                case _root_.com.daml.quickstart.iou.model.IouTrade.IouTrade_Accept(quoteIouCid) => quoteIouCid
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
