/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package IouTrade {
    final case class TradeProposal_Reject() extends ` lfdomainapi`.ValueRef

    object TradeProposal_Reject extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function0[_root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`];
          new $anon()
        }
      };
      implicit val `TradeProposal_Reject Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject] {
          override def write(value: _root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject): ` rpcvalue`.Value.Sum = ` record`();
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject] = argValue.record.flatMap(((x$5) => _root_.scala.Some(TradeProposal_Reject())))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.IouTrade, "IouTrade", "TradeProposal_Reject");
      implicit def `TradeProposal_Reject LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject] = {
            object `view ` extends view[lte.Field];
            lte.emptyRecord(` dataTypeId`, (() => _root_.com.daml.quickstart.iou.model.IouTrade.TradeProposal_Reject()))
          }
        };
        new $anon()
      }
    }
  }
}
