/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package Iou {
    final case class Iou_AddObserver(newObserver: ` lfdomainapi`.Primitive.Party) extends ` lfdomainapi`.ValueRef

    object Iou_AddObserver extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.Party, _root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val newObserver: ` C`[` lfdomainapi`.Primitive.Party];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val newObserver = ` f`(` view`.newObserver)
          };
          new $anon()
        }
      };
      implicit val `Iou_AddObserver Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] {
          override def write(value: _root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("newObserver", ` lfdomainapi`.Value.encode(value.newObserver)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "newObserver"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv0) match {
                case _root_.scala.Some(newObserver) => Some(Iou_AddObserver(newObserver))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.Iou, "Iou", "Iou_AddObserver");
      implicit def `Iou_AddObserver LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] = {
            object `view ` extends view[lte.Field] {
              val newObserver = lte.field("newObserver", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver] = lte.RecordFields.xmapN(lte.fields(`view `.newObserver))({
                case newObserver => _root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver(newObserver)
              })({
                case _root_.com.daml.quickstart.iou.model.Iou.Iou_AddObserver(newObserver) => newObserver
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
